In [8]:
# Packages
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import requests as req
from bs4 import BeautifulSoup as bs 
import json

In [4]:
df = pd.read_csv('US_youtube_trending_data.csv')

In [ ]:
df.head()

,video_id,title,publishedAt,channelId,channelTitle,categoryId,trending_date,tags,view_count,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,description
0,3C66w5Z0ixs,I ASKED HER TO BE MY GIRLFRIEND...,2020-08-11T19:20:14Z,UCvtRTOMP2TqYqu51xNrqAzg,Brawadis,22,2020-08-12T00:00:00Z,brawadis|prank|basketball|skits|ghost|funny vi...,1514614,156908,5855,35313,https://i.ytimg.com/vi/3C66w5Z0ixs/default.jpg,False,False,SUBSCRIBE to BRAWADIS ▶ http://bit.ly/Subscrib...
1,M9Pmf9AB4Mo,Apex Legends | Stories from the Outlands – “Th...,2020-08-11T17:00:10Z,UC0ZV6M2THA81QT9hrVWJG3A,Apex Legends,20,2020-08-12T00:00:00Z,Apex Legends|Apex Legends characters|new Apex ...,2381688,146739,2794,16549,https://i.ytimg.com/vi/M9Pmf9AB4Mo/default.jpg,False,False,"While running her own modding shop, Ramya Pare..."
2,J78aPJ3VyNs,I left youtube for a month and THIS is what ha...,2020-08-11T16:34:06Z,UCYzPXprvl5Y-Sf0g4vX-m6g,jacksepticeye,24,2020-08-12T00:00:00Z,jacksepticeye|funny|funny meme|memes|jacksepti...,2038853,353787,2628,40221,https://i.ytimg.com/vi/J78aPJ3VyNs/default.jpg,False,False,I left youtube for a month and this is what ha...
3,kXLn3HkpjaA,XXL 2020 Freshman Class Revealed - Official An...,2020-08-11T16:38:55Z,UCbg_UMjlHJg_19SZckaKajg,XXL,10,2020-08-12T00:00:00Z,xxl freshman|xxl freshmen|2020 xxl freshman|20...,496771,23251,1856,7647,https://i.ytimg.com/vi/kXLn3HkpjaA/default.jpg,False,False,Subscribe to XXL → http://bit.ly/subscribe-xxl...
4,VIUo6yapDbc,Ultimate DIY Home Movie Theater for The LaBran...,2020-08-11T15:10:05Z,UCDVPcEbVLQgLZX0Rt6jo34A,Mr. Kate,26,2020-08-12T00:00:00Z,The LaBrant Family|DIY|Interior Design|Makeove...,1123889,45802,964,2196,https://i.ytimg.com/vi/VIUo6yapDbc/default.jpg,False,False,Transforming The LaBrant Family's empty white ...

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 268787 entries, 0 to 268786
Data columns (total 16 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   video_id           268787 non-null  str
 1   title              268787 non-null  str
 2   publishedAt        268787 non-null  str
 3   channelId          268787 non-null  str
 4   channelTitle       268787 non-null  str
 5   categoryId         268787 non-null  int64
 6   trending_date      268787 non-null  str
 7   tags               268787 non-null  str
 8   view_count         268787 non-null  int64
 9   likes              268787 non-null  int64
 10  dislikes           268787 non-null  int64
 11  comment_count      268787 non-null  int64
 12  thumbnail_link     268787 non-null  str
 13  comments_disabled  268787 non-null  bool
 14  ratings_disabled   268787 non-null  bool
 15  description        264238 non-null  str
dtypes: bool(2), int64(5), str(9)
memory usage: 29.2 MB

In [10]:
with open("BR_category_id.json") as f:
    categories = json.load(f)

print(categories)

{'kind': 'youtube#videoCategoryListResponse', 'etag': 'kBCr3I9kLHHU79W4Ip5196LDptI', 'items': [{'kind': 'youtube#videoCategory', 'etag': 'IfWa37JGcqZs-jZeAyFGkbeh6bc', 'id': '1', 'snippet': {'title': 'Film & Animation', 'assignable': True, 'channelId': 'UCBR8-60-B28hp2BmDPdntcQ'}}, {'kind': 'youtube#videoCategory', 'etag': '5XGylIs7zkjHh5940dsT5862m1Y', 'id': '2', 'snippet': {'title': 'Autos & Vehicles', 'assignable': True, 'channelId': 'UCBR8-60-B28hp2BmDPdntcQ'}}, {'kind': 'youtube#videoCategory', 'etag': 'HCjFMARbBeWjpm6PDfReCOMOZGA', 'id': '10', 'snippet': {'title': 'Music', 'assignable': True, 'channelId': 'UCBR8-60-B28hp2BmDPdntcQ'}}, {'kind': 'youtube#videoCategory', 'etag': 'ra8H7xyAfmE2FewsDabE3TUSq10', 'id': '15', 'snippet': {'title': 'Pets & Animals', 'assignable': True, 'channelId': 'UCBR8-60-B28hp2BmDPdntcQ'}}, {'kind': 'youtube#videoCategory', 'etag': '7mqChSJogdF3hSIL-88BfDE-W8M', 'id': '17', 'snippet': {'title': 'Sports', 'assignable': True, 'channelId': 'UCBR8-60-B28hp2BmDPdntcQ'}}, {'kind': 'youtube#videoCategory', 'etag': '0Z6uGkj97NgjD-X3pkA-nL18Hqk', 'id': '18', 'snippet': {'title': 'Short Movies', 'assignable': False, 'channelId': 'UCBR8-60-B28hp2BmDPdntcQ'}}, {'kind': 'youtube#videoCategory', 'etag': 'K_-7stg0kIU7eUBOPUa6j5fqIMQ', 'id': '19', 'snippet': {'title': 'Travel & Events', 'assignable': True, 'channelId': 'UCBR8-60-B28hp2BmDPdntcQ'}}, {'kind': 'youtube#videoCategory', 'etag': 'I3IL9xGIM3MsULlqR4tvCsEKv98', 'id': '20', 'snippet': {'title': 'Gaming', 'assignable': True, 'channelId': 'UCBR8-60-B28hp2BmDPdntcQ'}}, {'kind': 'youtube#videoCategory', 'etag': 'D1W6tq5mMMCV0wtNxf9A6g9wWjU', 'id': '21', 'snippet': {'title': 'Videoblogging', 'assignable': False, 'channelId': 'UCBR8-60-B28hp2BmDPdntcQ'}}, {'kind': 'youtube#videoCategory', 'etag': 'QMEBz6mxVdklVaq8JwesPEw_4nI', 'id': '22', 'snippet': {'title': 'People & Blogs', 'assignable': True, 'channelId': 'UCBR8-60-B28hp2BmDPdntcQ'}}, {'kind': 'youtube#videoCategory', 'etag': 'v2n6q4JttoL4uUbazrcxNQRGPZk', 'id': '23', 'snippet': {'title': 'Comedy', 'assignable': True, 'channelId': 'UCBR8-60-B28hp2BmDPdntcQ'}}, {'kind': 'youtube#videoCategory', 'etag': 'Qi1csjh-POReitZEbR7CUw7dmao', 'id': '24', 'snippet': {'title': 'Entertainment', 'assignable': True, 'channelId': 'UCBR8-60-B28hp2BmDPdntcQ'}}, {'kind': 'youtube#videoCategory', 'etag': 'IbGXblQi8v_nOsXjirhul1NVcH8', 'id': '25', 'snippet': {'title': 'News & Politics', 'assignable': True, 'channelId': 'UCBR8-60-B28hp2BmDPdntcQ'}}, {'kind': 'youtube#videoCategory', 'etag': 'gYzt8dB8mlod-84ipMtjynYe9xU', 'id': '26', 'snippet': {'title': 'Howto & Style', 'assignable': True, 'channelId': 'UCBR8-60-B28hp2BmDPdntcQ'}}, {'kind': 'youtube#videoCategory', 'etag': 'hHUhloYhyMMqVkQ4LH9sr3aRQoU', 'id': '27', 'snippet': {'title': 'Education', 'assignable': True, 'channelId': 'UCBR8-60-B28hp2BmDPdntcQ'}}, {'kind': 'youtube#videoCategory', 'etag': 'KEdEtUd4WGk_aACrYI03UhGE33w', 'id': '28', 'snippet': {'title': 'Science & Technology', 'assignable': True, 'channelId': 'UCBR8-60-B28hp2BmDPdntcQ'}}, {'kind': 'youtube#videoCategory', 'etag': 'tMfbFvkfuPP8YnUEqpr0gcR6aWU', 'id': '30', 'snippet': {'title': 'Movies', 'assignable': False, 'channelId': 'UCBR8-60-B28hp2BmDPdntcQ'}}, {'kind': 'youtube#videoCategory', 'etag': 'totPMF_82XTvVFy0ExFgoKhTklM', 'id': '31', 'snippet': {'title': 'Anime/Animation', 'assignable': False, 'channelId': 'UCBR8-60-B28hp2BmDPdntcQ'}}, {'kind': 'youtube#videoCategory', 'etag': 'LNgRKNynxC50MeYV9e6XLPX9JC4', 'id': '32', 'snippet': {'title': 'Action/Adventure', 'assignable': False, 'channelId': 'UCBR8-60-B28hp2BmDPdntcQ'}}, {'kind': 'youtube#videoCategory', 'etag': 'harT7v7A6516SPdkqp81Xy5yfBw', 'id': '33', 'snippet': {'title': 'Classics', 'assignable': False, 'channelId': 'UCBR8-60-B28hp2BmDPdntcQ'}}, {'kind': 'youtube#videoCategory', 'etag': 'M6Y5Av0CP45r5GgpzamLfHj41y4', 'id': '34', 'snippet': {'title': 'Comedy', 'assignable': False, 'channelId': 'UCBR8-60-B28hp2BmDPdntcQ'}}, {'kind': 'youtube#videoCategory', 'etag': 'ZFbZGeeLYWolvmCLQM7m8Yio104', 'id': '35', 'snippet': {'title': 'Documentary', 'assignable': False, 'channelId': 'UCBR8-60-B28hp2BmDPdntcQ'}}, {'kind': 'youtube#videoCategory', 'etag': 'FD7naICnxxl8HOnZZJAzrWplzuU', 'id': '36', 'snippet': {'title': 'Drama', 'assignable': False, 'channelId': 'UCBR8-60-B28hp2BmDPdntcQ'}}, {'kind': 'youtube#videoCategory', 'etag': '7fvdoCRRWE89SpB5UaOY8gGdbk0', 'id': '37', 'snippet': {'title': 'Family', 'assignable': False, 'channelId': 'UCBR8-60-B28hp2BmDPdntcQ'}}, {'kind': 'youtube#videoCategory', 'etag': 'H6d6HrYDy3EAVAxQR8Z-ShEva1k', 'id': '38', 'snippet': {'title': 'Foreign', 'assignable': False, 'channelId': 'UCBR8-60-B28hp2BmDPdntcQ'}}, {'kind': 'youtube#videoCategory', 'etag': 'Z3yra5IR8n2bkjvv3ZheAOQ-tUk', 'id': '39', 'snippet': {'title': 'Horror', 'assignable': False, 'channelId': 'UCBR8-60-B28hp2BmDPdntcQ'}}, {'kind': 'youtube#videoCategory', 'etag': '3F8eda4xnGzGFmlpsFaf5_YpOgU', 'id': '40', 'snippet': {'title': 'Sci-Fi/Fantasy', 'assignable': False, 'channelId': 'UCBR8-60-B28hp2BmDPdntcQ'}}, {'kind': 'youtube#videoCategory', 'etag': 'HwuNLGhBJ4PZCEurr-SoqvHuKx8', 'id': '41', 'snippet': {'title': 'Thriller', 'assignable': False, 'channelId': 'UCBR8-60-B28hp2BmDPdntcQ'}}, {'kind': 'youtube#videoCategory', 'etag': 'qJ2eDOZWUDj8fbFYAIG_yzPCYRc', 'id': '42', 'snippet': {'title': 'Shorts', 'assignable': False, 'channelId': 'UCBR8-60-B28hp2BmDPdntcQ'}}, {'kind': 'youtube#videoCategory', 'etag': '2sKmjip5q7FHJgqkHvnpMDgmddE', 'id': '43', 'snippet': {'title': 'Shows', 'assignable': False, 'channelId': 'UCBR8-60-B28hp2BmDPdntcQ'}}, {'kind': 'youtube#videoCategory', 'etag': '3IaZjRK8JeIkLMfRDX57P4FFb9A', 'id': '44', 'snippet': {'title': 'Trailers', 'assignable': False, 'channelId': 'UCBR8-60-B28hp2BmDPdntcQ'}}]}

In [12]:
cat_df = pd.DataFrame([
    {
        "category_id": int(item["id"]),
        "category_name": item["snippet"]["title"]
    }
    for item in categories["items"]
])

print(cat_df)

    category_id         category_name
0             1      Film & Animation
1             2      Autos & Vehicles
2            10                 Music
3            15        Pets & Animals
4            17                Sports
5            18          Short Movies
6            19       Travel & Events
7            20                Gaming
8            21         Videoblogging
9            22        People & Blogs
10           23                Comedy
11           24         Entertainment
12           25       News & Politics
13           26         Howto & Style
14           27             Education
15           28  Science & Technology
16           30                Movies
17           31       Anime/Animation
18           32      Action/Adventure
19           33              Classics
20           34                Comedy
21           35           Documentary
22           36                 Drama
23           37                Family
24           38               Foreign
25           39                Horror
26           40        Sci-Fi/Fantasy
27           41              Thriller
28           42                Shorts
29           43                 Shows
30           44              Trailers

In [14]:
print(df.columns)
print(cat_df.columns)

Index(['video_id', 'title', 'publishedAt', 'channelId', 'channelTitle',
       'categoryId', 'trending_date', 'tags', 'view_count', 'likes',
       'dislikes', 'comment_count', 'thumbnail_link', 'comments_disabled',
       'ratings_disabled', 'description'],
      dtype='str')
Index(['category_id', 'category_name'], dtype='str')

In [15]:
# Rename to match cat_df
df = df.rename(columns={"categoryId": "category_id"})
df["category_id"] = df["category_id"].astype(int)
cat_df["category_id"] = cat_df["category_id"].astype(int)

In [18]:
df = df.merge(cat_df, on="category_id", how="left")
print(df[["category_id", "category_name"]].head())

   category_id   category_name
0           22  People & Blogs
1           20          Gaming
2           24   Entertainment
3           10           Music
4           26   Howto & Style

In [19]:
df.head()

,video_id,title,publishedAt,channelId,channelTitle,category_id,trending_date,tags,view_count,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,description,category_name_x,category_name_y,category_name
0,3C66w5Z0ixs,I ASKED HER TO BE MY GIRLFRIEND...,2020-08-11T19:20:14Z,UCvtRTOMP2TqYqu51xNrqAzg,Brawadis,22,2020-08-12T00:00:00Z,brawadis|prank|basketball|skits|ghost|funny vi...,1514614,156908,5855,35313,https://i.ytimg.com/vi/3C66w5Z0ixs/default.jpg,False,False,SUBSCRIBE to BRAWADIS ▶ http://bit.ly/Subscrib...,People & Blogs,People & Blogs,People & Blogs
1,M9Pmf9AB4Mo,Apex Legends | Stories from the Outlands – “Th...,2020-08-11T17:00:10Z,UC0ZV6M2THA81QT9hrVWJG3A,Apex Legends,20,2020-08-12T00:00:00Z,Apex Legends|Apex Legends characters|new Apex ...,2381688,146739,2794,16549,https://i.ytimg.com/vi/M9Pmf9AB4Mo/default.jpg,False,False,"While running her own modding shop, Ramya Pare...",Gaming,Gaming,Gaming
2,J78aPJ3VyNs,I left youtube for a month and THIS is what ha...,2020-08-11T16:34:06Z,UCYzPXprvl5Y-Sf0g4vX-m6g,jacksepticeye,24,2020-08-12T00:00:00Z,jacksepticeye|funny|funny meme|memes|jacksepti...,2038853,353787,2628,40221,https://i.ytimg.com/vi/J78aPJ3VyNs/default.jpg,False,False,I left youtube for a month and this is what ha...,Entertainment,Entertainment,Entertainment
3,kXLn3HkpjaA,XXL 2020 Freshman Class Revealed - Official An...,2020-08-11T16:38:55Z,UCbg_UMjlHJg_19SZckaKajg,XXL,10,2020-08-12T00:00:00Z,xxl freshman|xxl freshmen|2020 xxl freshman|20...,496771,23251,1856,7647,https://i.ytimg.com/vi/kXLn3HkpjaA/default.jpg,False,False,Subscribe to XXL → http://bit.ly/subscribe-xxl...,Music,Music,Music
4,VIUo6yapDbc,Ultimate DIY Home Movie Theater for The LaBran...,2020-08-11T15:10:05Z,UCDVPcEbVLQgLZX0Rt6jo34A,Mr. Kate,26,2020-08-12T00:00:00Z,The LaBrant Family|DIY|Interior Design|Makeove...,1123889,45802,964,2196,https://i.ytimg.com/vi/VIUo6yapDbc/default.jpg,False,False,Transforming The LaBrant Family's empty white ...,Howto & Style,Howto & Style,Howto & Style

In [ ]:
# EDA and visualizations on Kaggle data 
print(df.shape)      
print(df.columns)      
df.info()
df.describe()

(268787, 19)
Index(['video_id', 'title', 'publishedAt', 'channelId', 'channelTitle',
       'category_id', 'trending_date', 'tags', 'view_count', 'likes',
       'dislikes', 'comment_count', 'thumbnail_link', 'comments_disabled',
       'ratings_disabled', 'description', 'category_name_x', 'category_name_y',
       'category_name'],
      dtype='str')
<class 'pandas.DataFrame'>
RangeIndex: 268787 entries, 0 to 268786
Data columns (total 19 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   video_id           268787 non-null  str
 1   title              268787 non-null  str
 2   publishedAt        268787 non-null  str
 3   channelId          268787 non-null  str
 4   channelTitle       268787 non-null  str
 5   category_id        268787 non-null  int64
 6   trending_date      268787 non-null  str
 7   tags               268787 non-null  str
 8   view_count         268787 non-null  int64
 9   likes              268787 non-null  int64
 10  dislikes           268787 non-null  int64
 11  comment_count      268787 non-null  int64
 12  thumbnail_link     268787 non-null  str
 13  comments_disabled  268787 non-null  bool
 14  ratings_disabled   268787 non-null  bool
 15  description        264238 non-null  str
 16  category_name_x    268667 non-null  str
 17  category_name_y    268667 non-null  str
 18  category_name      268667 non-null  str
dtypes: bool(2), int64(5), str(12)
memory usage: 35.4 MB

         category_id    view_count         likes       dislikes  comment_count
count  268787.000000  2.687870e+05  2.687870e+05  268787.000000   2.687870e+05
mean       18.743511  2.734467e+06  1.314697e+05    1134.277495   1.014303e+04
std         6.786562  9.794087e+06  4.539469e+05    8047.291315   7.260853e+04
min         1.000000  0.000000e+00  0.000000e+00       0.000000   0.000000e+00
25%        17.000000  4.725410e+05  1.796300e+04       0.000000   1.280000e+03
50%        20.000000  9.368710e+05  4.020500e+04       0.000000   2.754000e+03
75%        24.000000  2.106178e+06  9.877300e+04     467.000000   6.386000e+03
max        29.000000  1.407644e+09  1.602153e+07  879354.000000   6.738537e+06

In [ ]:
# count missing values
missing = df.isnull().sum().sort_values(ascending=False)
print(missing)

description          4549
category_name_y       120
category_name         120
category_name_x       120
publishedAt             0
video_id                0
title                   0
channelId               0
channelTitle            0
category_id             0
trending_date           0
dislikes                0
likes                   0
view_count              0
tags                    0
ratings_disabled        0
comments_disabled       0
thumbnail_link          0
comment_count           0
dtype: int64

In [ ]:
# count of categories 
df["category_name"].value_counts().head(10)

category_name
Entertainment           53934
Gaming                  53242
Music                   43398
Sports                  31327
People & Blogs          22653
Comedy                  13183
Film & Animation        10923
News & Politics          9669
Science & Technology     8156
Howto & Style            7100
Name: count, dtype: int64

In [ ]:
# stats for numeric columns
df[["view_count", "likes", "dislikes", "comment_count"]].describe()

         view_count         likes       dislikes  comment_count
count  2.687870e+05  2.687870e+05  268787.000000   2.687870e+05
mean   2.734467e+06  1.314697e+05    1134.277495   1.014303e+04
std    9.794087e+06  4.539469e+05    8047.291315   7.260853e+04
min    0.000000e+00  0.000000e+00       0.000000   0.000000e+00
25%    4.725410e+05  1.796300e+04       0.000000   1.280000e+03
50%    9.368710e+05  4.020500e+04       0.000000   2.754000e+03
75%    2.106178e+06  9.877300e+04     467.000000   6.386000e+03
max    1.407644e+09  1.602153e+07  879354.000000   6.738537e+06

In [ ]:
# correlaation between numeric vars
corr = df[["view_count", "likes", "dislikes", "comment_count"]].corr()
print(corr)

               view_count     likes  dislikes  comment_count
view_count       1.000000  0.801696  0.311416       0.469340
likes            0.801696  1.000000  0.381459       0.684341
dislikes         0.311416  0.381459  1.000000       0.416830
comment_count    0.469340  0.684341  0.416830       1.000000

In [ ]:
# Top 10 most viewed videos
df.sort_values("view_count", ascending=False)[["title", "view_count"]].head(10)

                                   title  view_count
266187      Discord Loot Boxes are here.  1407643634
266388      Discord Loot Boxes are here.  1406329649
265987      Discord Loot Boxes are here.   628718636
152788      BLACKPINK - ‘Pink Venom’ M/V   277791741
152568      BLACKPINK - ‘Pink Venom’ M/V   273162966
152365      BLACKPINK - ‘Pink Venom’ M/V   268758295
152175      BLACKPINK - ‘Pink Venom’ M/V   264459017
56374   BTS (방탄소년단) 'Butter' Official MV   264407389
151968      BLACKPINK - ‘Pink Venom’ M/V   260126694
151773      BLACKPINK - ‘Pink Venom’ M/V   255524865

In [ ]:
# Youtube API Stuff **ASK PROF ABOUT THIS**

from googleapiclient.discovery import build 
from dotenv import load_dotenv
import os
load_dotenv()

api_key = os.getenv("YOUTUBE_API_KEY")
                    
youtube = build("youtube", "v3", developerKey=api_key)

In [ ]:
#Pull video data check
video_ids = "Ks-_Mh1QhMc,VIDEO_ID_2"

request = youtube.videos().list(
    part="snippet,statistics",
    id=video_ids
)

response = request.execute()

for item in response["items"]:
    title = item["snippet"]["title"]
    views = item["statistics"].get("viewCount")
    likes = item["statistics"].get("likeCount")
    
    print(title, views, likes)

Your Body Language May Shape Who You Are | Amy Cuddy | TED 28103560 521967

In [33]:
video_ids = df["video_id"].dropna().unique()[:50]  # limit for testing

# API allows up to 50 IDs per request
video_id_batches = [video_ids[i:i+50] for i in range(0, len(video_ids), 50)]

In [34]:
all_results = []

for batch in video_id_batches:
    request = youtube.videos().list(
        part="snippet,statistics",
        id=",".join(batch)
    )
    
    response = request.execute()
    
    for item in response["items"]:
        all_results.append({
            "video_id": item["id"],
            "title": item["snippet"]["title"],
            "views": item["statistics"].get("viewCount"),
            "likes": item["statistics"].get("likeCount"),
            "comments": item["statistics"].get("commentCount")
        })

In [35]:
api_df = pd.DataFrame(all_results)

In [36]:
api_df.head()

,video_id,title,views,likes,comments
0,M9Pmf9AB4Mo,Apex Legends | Stories from the Outlands – “Th...,5803964,199683,16325
1,J78aPJ3VyNs,I left youtube for a month and THIS is what ha...,4184609,474242,42342
2,kXLn3HkpjaA,XXL 2020 Freshman Class Revealed - Official An...,1755677,42039,9367
3,VIUo6yapDbc,Ultimate DIY Home Movie Theater for The LaBran...,2876873,72388,2703
4,w-aidBdvZo8,I Haven't Been Honest About My Injury.. Here's...,2776968,150942,11620

In [ ]:
# EDA for API data 

print(api_df.shape)
print(api_df.columns)
api_df.info()
api_df.describe()

(47, 5)
Index(['video_id', 'title', 'views', 'likes', 'comments'], dtype='str')
<class 'pandas.DataFrame'>
RangeIndex: 47 entries, 0 to 46
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   video_id  47 non-null     str
 1   title     47 non-null     str
 2   views     47 non-null     str
 3   likes     47 non-null     str
 4   comments  47 non-null     str
dtypes: str(5)
memory usage: 2.0 KB

,video_id,title,views,likes,comments
count,47,47,47,47,47
unique,47,47,47,47,47
top,M9Pmf9AB4Mo,Apex Legends | Stories from the Outlands – “Th...,5803964,199683,16325
freq,1,1,1,1,1

In [ ]:
# NOTE: 
# API Data is more up to date than Kaggle data, so view counts and likes are higher.
# Use kaggle data for details on videos, and API data for up to date stats on video performance. 
#**ASK Prof about API key and how to hide before I push to github